version: '3.4'

services:
  dev.store.web:
    image: ${DOCKER_REGISTRY-}devstoreweb
    ports:
      - 1001:80
    build:
      context: .
      dockerfile: src/Dev.Store.Web/Dockerfile

  dev.store.web.public:
    image: ${DOCKER_REGISTRY-}devstorewebpublic
    ports:
      - 1002:80
    build:
      context: .
      dockerfile: src/Dev.Store.Web.Public/Dockerfile

