name: Deploy

on:
  push:
    branches: [ deploy ]
  release:
    types:
      - published
        
jobs:

  buildAdminUI:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/seyit-tekce/devstoreweb
          tag-sha: true
          tag-edge: false
          tag-latest: true
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
        
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
          
      - name: Abp Install Abp Cli
        run: dotnet tool install -g Volo.Abp.Cli
        
      - name: Abp Install Libs
        run: abp install-libs        
      
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }} 
          file: ./Build/Dev.Store.Web/Dockerfile
          
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Build/Dev.Store.Web/Dockerfile

  buildFrontUI:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/seyit-tekce/devstorewebpublic
          tag-sha: true
          tag-edge: false
          tag-latest: true
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Abp Install Abp Cli
        run: dotnet tool install -g Volo.Abp.Cli
        
      - name: Abp Install Libs
        run: abp install-libs

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }} 
          file: ./Build/Dev.Store.Web.Public/Dockerfile
          
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Build/Dev.Store.Web.Public/Dockerfile
            
  buildMigrator:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/seyit-tekce/devstoremigrator
          tag-sha: true
          tag-edge: false
          tag-latest: true
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}

       
        
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }} 
          file: ./Build/Dev.Store.DbMigrator/Dockerfile
          
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Build/Dev.Store.DbMigrator/Dockerfile
            

  
